### ISSUE TITLE
Avoid hardcoding output resolution if out_proj is defined

### ISSUE THREAD

**Issue by dshean** [uw-cryo/opentopo_dem#3]
Some of the supported DEMs are 90 m products.  And with oversampling in E-W direction toward the poles in original EPSG:4326 grids, can potentially do better than 30 m.  Could just let GDAL compute the appropriate output tr.

https://github.com/uw-cryo/opentopo_dem/blob/main/opentopo_dem/opentopo_utils.py#L54

**Comment by ShashankBice** [comment]
This is a good point, we can let it to default to projected resolution determined by gdalwarp. I will work on this!

**Comment by ShashankBice** [comment]
Thanks, this has been implemented in the latest commits!
